global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'social-trend-agent'
    static_configs:
      - targets: ['trend-agent:8001']
    scrape_interval: 30s
    metrics_path: /metrics
    
  - job_name: 'social-trend-agent-api'
    static_configs:
      - targets: ['trend-agent:8000']
    scrape_interval: 60s
    metrics_path: /metrics
    
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

